class ExceptionExistMultipleMDFiles(Exception): pass
class ExceptionExistsDirectory(Exception): pass
class ExceptionExistsDirectoryInDirectory(Exception): pass
class ExceptionExistsDirectoryOrFile(Exception): pass
class ExceptionExistsFile(Exception): pass
class ExceptionListNotAllString(Exception): pass
class ExceptionMDFileContent(Exception): pass
class ExceptionMDFileNoContent(Exception): pass
class ExceptionNotAbsolutePath(Exception): pass
class ExceptionNotExistsDirectory(Exception): pass
class ExceptionNotExistsDirectoryOrFile(Exception): pass
class ExceptionNotExistsFile(Exception): pass
class ExceptionNotExistsFileExtension(Exception): pass
class ExceptionNotExistsImage(Exception): pass
class ExceptionNotExistsImageFile(Exception): pass
class ExceptionNotExistsMDFile(Exception): pass
class ExceptionNotExistsOpenMode(Exception): pass
class ExceptionNotSamePath(Exception): pass
class ExceptionSamePath(Exception): pass
class ExceptionNotExistsPrefix(Exception): pass